### ISSUE TITLE
Error when trying to establish account or donate for SSL cert.

### ISSUE THREAD

**Issue by Reddinr74** [issus/altium-library#10]
I received and error when the desktop application tries to send the activation email.  I double checked the email address and even tried an alternate.  The error message:  "an error has occurred".  Not that it helps...  My sys. is Windows 7,64 Bit.  Also, when attempting to donate for the SSL cert., gofundme says there is some sort of problem with the account.  Probably something simple.

**Comment by issus** [comment]
Ugh, totally missed this issue :( Please see #11 if you're still having issues with the activation email - I'd love to get that one solved. Thanks for letting me know about the gofundme issue - that explains the complete lack of donations for the past 6 months! I think I've resolved the issue now.
