### ISSUE TITLE
0805 Capacitors have wrong footprint

### ISSUE THREAD

**Issue by dookei** [issus/altium-library#103]
Hi There,
the 0805 SMD capacitors have very less distance between pads. This will cause shorts when using Cu with 105um.
Would it be possible to increase the distance between the pads?

**Comment by issus** [comment]
0805 Capacitors footprint is to the manufacturers recommended footprint (yageos i believe)

**Comment by legier** [comment]
@issus that does not mean it is recommended for every board. Here is a screenshot from a manufacturer datasheet. You have 3 different dimensions based on desired density level. Typically you should be able to route 2 traces between 0805 pads, currently you cannot route even single one.
![image](https://github.com/issus/altium-library/assets/24257432/599c26f4-c04b-4ca5-8adf-98967785bf9f)
