### ISSUE TITLE
How to install all of it for complete offline use?

### ISSUE THREAD

**Issue by Unknown78** [issus/altium-library#107]
Is it possible?

**Comment by mikhailmihalkov** [comment]
Convert to integrated lib

**Comment by Unknown78** [comment]
How to convert it?

**Comment by mikhailmihalkov** [comment]
https://www.altium.com/documentation/altium-designer/database-library-migration-tools 
I advise you not to convert everything at once, divide it into 2-3 parts into folders, otherwise the altium is closed

**Comment by Unknown78** [comment]
@mikhailmihalkov Why it closed?

**Comment by mikhailmihalkov** [comment]
> @mikhailmihalkovПочему он закрылся?
It closes for everyone not only I have this glitch of the work of the altium at large libraries... From version to version, the bug remains...
