### ISSUE TITLE
New User activation code not sent and error

### ISSUE THREAD

**Issue by LGKev** [issus/altium-library#11]
similar to issue 10

I have attempted to sign up, but cannot see the send button in the window (its below bottom of the window and does not allow for scrolling)
 i just hit tab 2 times and then enter, which takes me to the activation code window. 

No activation email sent so I hit resend. An error has occurred shows, without any email sent.

I checked spam.

![desktop create account altium](https://user-images.githubusercontent.com/14641166/29392376-5dc1130a-82b2-11e7-8911-8bc573600d65.PNG)

![error occured resend](https://user-images.githubusercontent.com/14641166/29392380-628bca60-82b2-11e7-9c16-e48cb1189164.PNG)

Also is there a lost username/password? I want to reuse the same email I have been using but forgot my password and get the following error:
![no reuse email](https://user-images.githubusercontent.com/14641166/29392487-fdd76114-82b2-11e7-8ab6-48291e125799.PNG)

**Comment by logictom** [comment]
Tried to sign up today, same issue - "An error has occurred." and I never received an email

**Comment by Saruniks** [comment]
same problem

**Comment by yanw4tanabe** [comment]
same problem here

**Comment by issus** [comment]
Closing as this is an issue for the desktop manager software: https://github.com/issus/CelestialADB-Desktop

I'm about to push a code change up which will enable scaling so it can run on a 768-pixel high screen, however, I won't be pushing a new version just yet.

**Comment by sanketrghadshi** [comment]
I am receciving any activation code. Its says username/ email does notvexist

**Comment by sanketrghadshi** [comment]
I am not receiving any activation code. It says username/ email not valid

**Comment by luccasc** [comment]
Hello, i have same problem. I am not receiving any activation code and It says username/ email not valid.
Help. please.

**Comment by p-vc** [comment]
Hello,

Been trying for several days, succeeded in installing the program, completing the form, click register, then end up in the activate account window, but never getting any email.  Resend simply shows a please wait and I end up in the same window again.

Tried with 3 diffrnt emails/names etc, no succes.
Is this still active?

**Comment by G-S-E** [comment]
I used gmail.com with success, but some other domains fail.

**Comment by GHardman** [comment]
Same problem here. Tried with gmail.com and another email, but no code sent, just the message about email not being valid.
