### ISSUE TITLE
Password not complex enough for AzureSQL

### ISSUE THREAD

**Issue by motyr1** [issus/altium-library#12]
Hi

I am having a problem with registering the account. All the time I am getting error message:
"Password not complex enough for AzureSQL"

I have tried many passwords but still the same.
I have even tried 64 characters passwords like this:
"z8yE3txadzFMXDGPf0W4eC5C9Ny7rpQOmdjdwEdz3H9RaFuftg8yG1YGEnBTChxM" still the same.

Any suggestions ?

**Comment by Levitrevisan** [comment]
try using the "-" character at the end, my password is like "SomeWord1234-" and works fine.
