### ISSUE TITLE
Error found in microphone CMA-4544PF-W pcb lib

### ISSUE THREAD

**Issue by pinganbo** [issus/altium-library#121]
Error found in microphone CMA-4544PF-W pcb lib. GND and OUT are reversed.
![微信图片_20230609125815](https://github.com/issus/altium-library/assets/64126453/f7b94a96-c756-4894-bce9-773dff3c8410)

**Comment by issus** [comment]
You're right! That's a bottom view drawing in the middle, not a top view. Fixed footprint has been pushed to the repository.
