### ISSUE TITLE
Can't connect to server for some reason.

### ISSUE THREAD

**Issue by benz901123** [issus/altium-library#13]
Hi all,

After spending my whole afternoon trying to get this to work, I gave up. I am unable to connect to the server. 

I created my .udl file through celestial desktop manager 
![image](https://user-images.githubusercontent.com/32714408/31454826-b0489ac6-aeae-11e7-9ba1-d38890d64a77.png)

I then double clicked on the udl file and clicked 'test connections'
![image](https://user-images.githubusercontent.com/32714408/31454686-2034ed68-aeae-11e7-931b-232ca7751947.png)

After waiting for about 5-10 secs, these are the error messages I am consistently getting. 
![image](https://user-images.githubusercontent.com/32714408/31454734-554202fc-aeae-11e7-9c91-59f9df467021.png)

![image](https://user-images.githubusercontent.com/32714408/31454872-d12ba6e8-aeae-11e7-88e3-33f1e7fe7027.png)

I re-read the instructions and the error section several times and am still unable to get this to work. I have disabled firewall to try this and it is still not working.

Please help me!

Thank you,
Benjamin

**Comment by issus** [comment]
Windows firewall, school/corporate firewall, or your ISP is blocking MSSQL's port (TCP:1433). This is common at Universities - contact helpdesk and they should be able to create an exception to csql.database.windows.net:1433 for your user, lab or machine :)
