### ISSUE TITLE
Component display is incomplete

### ISSUE THREAD

**Issue by QinWei98** [issus/altium-library#145]
I strictly followed the tutorial and used the latest library file pulled from Github, but when I needed to use the STM32U5 series microcontroller, I couldn't find it. However, I found the STM32U5 series package in the local pull path.
![1](https://github.com/user-attachments/assets/627fcc35-1b90-4b46-902f-021aeb0c27a6)
![2](https://github.com/user-attachments/assets/49d8333a-85fb-4335-9e35-1d87cee66e38)

**Comment by issus** [comment]
Just because there is a symbol there, it doesnt mean it has been added to the library. It may be awaiting a footprint to be made
