### ISSUE TITLE
Murata GRM31CR71H475KA12L has incorrect footprint in recent updates

### ISSUE THREAD

**Issue by NothingButGunpowder** [issus/altium-library#146]
I recently added the GRM31CR71H475KA12L to a design and Altium brought in the new footprint for one device and the old footprint for another device.  The two do not match; I believe the original is correct (I've had boards made with the old footprint).  Also, I don't know if the height of the new one is correct.  Ignore the overlapping silk in the image- this layout isn't complete.

The old footprint was 'CAP 1206_3216-0.8mm', and the new footprint is 'MURATA CAP GRM31M 1206_3216'
 
![image](https://github.com/user-attachments/assets/a9bf971c-2234-46a0-8ad8-0cb52b5c951f)

**Comment by issus** [comment]
Yes, you're right - the footprint was applied too widely - this should only be for the 1.2mm high GMR31M. I'll get the GRM31C's their own footprint today. The old footprint was generic and made to just one (possibly KEMETs) footprint recommendations, we're slowly expanding the capacitor footprints to match each manufacturer's recommendation for each series.

**Comment by issus** [comment]
Should be fixed now, if you can check

**Comment by NothingButGunpowder** [comment]
Yes, I can confirm the current check-in (c06f0fa47)  footprint looks like it will fit the cap.  Thanks for maintaining this excellent resource!

![image](https://github.com/user-attachments/assets/f404d269-7b50-4448-866b-894f4b7e92a7)
![image](https://github.com/user-attachments/assets/893d50d6-eda0-4f8e-8cf4-78f7bb64acc7)
