### ISSUE TITLE
Import Guide

### ISSUE THREAD

**Issue by yldzmuhammed** [issus/altium-library#15]
Hello

First of all, thank you for great effor and sharing such a great work.

I want to implement your library. But i am getting some erros when i install/implement to this library. 

I dont have any sql server on my computer. Should i?

Can you guide me from the zero point to do the necessary things?

I have added some components that you dont have in your lib and some of them on your to list components.

I will be wait for your reply. Thanks a lot..

**Comment by issus** [comment]
If you read the main page readme you'll be directed over to https://github.com/issus/CelestialADB-Desktop where you can register for access to the database and get your firewall rules all set automagically :)
