### ISSUE TITLE
[Suggestion] Add Yageo RC series resistors as Panasonic alternatives  

### ISSUE THREAD

**Issue by HiFiPhile** [issus/altium-library#16]
Hi,
I appreciate this great library.
Could you please add Yageo RC series resistors for common values and cases like 0402, 0603 and  0805?
I see there are already some Yageo resistors but most values are not present. 

Thanks very much and happy new year!

**Comment by ddavidebor** [comment]
Hi,

I wanted to thank you for the excel file as it's been very useful.
Davide
