### ISSUE TITLE
 Cannot open server 'csql'

### ISSUE THREAD

**Issue by KWAc** [issus/altium-library#21]
Hello,

I'm trying your open source library. Thank you for this ressource.

However, I have the following error when I try test the connection to the Azure server :
Cannot open server 'csql' requested by the login. Client with IP Adress 'xxxxxxxx' is not allowed to access the server. [...]

I already downloaded the Celestial Altium DB Deskstop software and it seems that my Azure access is valid.

Do you have a solution for this error ?

Thank you,

Cyril

**Comment by issus** [comment]
Are you using a proxy server on your computer? The server will only add a firewall rule for the IP address the webservices are called from, so if you have an external proxy that will be the IP address you're requesting to add.

**Comment by RadicalRedemption** [comment]
I am having the same issue, not using any proxy.
