### ISSUE TITLE
Please specify exactly what MSSQL software is required and how to install it

### ISSUE THREAD

**Issue by foobarbecue** [issus/altium-library#22]
The signup confirmation email said:

> If you have connection issues, then you may be missing the MSSQL driver on your computer, you can download it here:
> https://www.microsoft.com/en-us/download/details.aspx?id=29065 
> 

So I went to that page and clicked "Download." The resulting download, bizarrely, was just a confusing text file with, like, country road driving directions to the download, and a note saying: 

> please be certain to pick the appropriate component architecture for download.

I'd... like to be certain!? Either I need a better link, or more specific requirements info.

**Comment by issus** [comment]
Consider reading the wiki: https://github.com/issus/altium-library/wiki

**Comment by foobarbecue** [comment]
Looks like that is the necessary information. Would be great if the confirmation email (subject: Welcome to the Celestial Altium Databse) linked to that wiki page instead of the Microsoft page.

**Comment by zbrozek** [comment]
Though it would be great to have a HOWTO for a local installation, given that Azure seems to have less-than-stellar uptime.
