### ISSUE TITLE
Addressable RGB LED and mechanical keyswitch footprint

### ISSUE THREAD

**Issue by dennis97519** [issus/altium-library#24]
May I submit footprints and models for APA102-2020 RGB LEDS, and Kailh PG1350 switch sockets?

**Comment by issus** [comment]
If you have active digikey part numbers, then yes you can - as long as they have proper 3d models and the footprints/symbols conform to the readme/other parts. You can submit a pull request with the digikey part numbers :)

**Comment by dennis97519** [comment]
The LEDs have digikey part numbers, and I got the model from [here](https://grabcad.com/library/apa102-2020-rgb-led-1)

No digikey/mouser part number for the mechanical switch sockets though...

I guess nevermind then :P
