### ISSUE TITLE
issues in rectangular connector library

### ISSUE THREAD

**Issue by dennis97519** [issus/altium-library#25]
IDC box header .050" 10 POS doesn't have number of positions and number of rows filled in

CONN HEADER GH SIDE 2POS 1.25MM 3D view is only a box extrusion

**Comment by issus** [comment]
Do you have a part number for the IDC box header? Footprints all look good for everything 10 pin I can see.

Fixed the GHS connector, thanks for letting me know!

**Comment by dennis97519** [comment]
Thanks for fixing it!

For the IDC box header, I meant that the columns "Number of positions" and "Number of rows" are empty. They should have 10 and 2 filled in respectively.
