### ISSUE TITLE
Error " Microsoft SQL Server Native Client11.0" login failed for user " "

### ISSUE THREAD

**Issue by mhd-munzer** [issus/altium-library#26]
I had my library working for some time, but then I forgot my password and tried every single password I ever used, but still not working. Due to the fact that there is no restore password option, I created another account and activated it. The azure software is accepting my credentials but the udl is showing this error

![aaa](https://user-images.githubusercontent.com/25749890/43096789-c549d96a-8e7f-11e8-8adc-67b02e7ed48f.JPG)

I created another account after that, but still the same issue, is there anything I can do for that.

**Comment by vidavidorra** [comment]
Same problem here at the moment. I'm 100% sure I'm not behind a firewall or anything. When trying to login the desktop app I get the following error (`Data at the root level is invalid. Line 1, position 1.`. Same when trying to make a new account.

![image 1](https://user-images.githubusercontent.com/12871315/44507818-452d9100-a6ac-11e8-885c-a54fc794315e.png)

**Comment by yldzmuhammed** [comment]
I have same problem with @vidavidorra. Have you solved the problem?
