### ISSUE TITLE
Clarify dependencies

### ISSUE THREAD

**Issue by zbrozek** [issus/altium-library#31]
I get the following error, but only for this library. Other dblibs (Excel based) seem to work just fine, so at least some form of the dependencies have been satisfied. Is there some other runtime dependency?

![image](https://user-images.githubusercontent.com/4878259/46644410-fee5a180-cb34-11e8-9def-766067d30563.png)

**Comment by zbrozek** [comment]
In fact you need this:
https://www.microsoft.com/en-us/download/confirmation.aspx?id=50402

**Comment by yldzmuhammed** [comment]
Same issue here. But @zbrozek 's solution is not work for me!

**Comment by zbrozek** [comment]
I've stopped using this library. It seems to have gone unmaintained, and it's not possible to contribute.
