### ISSUE TITLE
Server is down?

### ISSUE THREAD

**Issue by hawkenlee** [issus/altium-library#39]
Is this project still running? I cannot contact with the server. How could I use the lib?

**Comment by hawkenlee** [comment]
![image](https://user-images.githubusercontent.com/20535801/65655928-867f3580-e050-11e9-9e37-c751321b6559.png)
My error!

**Comment by sasschary** [comment]
Issue seconded. I have been unable to connect, and the library website is showing the default Apache website rather than the normal Altium library website.

**Comment by mojtabashahbandari** [comment]
The online database will be up again?

**Comment by mojtabashahbandari** [comment]
Can anyone tell me what happened to the project server and database?

**Comment by gyohng** [comment]
The server crashed and there were no backups. Mark promised to publish the last downloaded database on github at some point. If you need it quicker, please ask on Discord.
