### ISSUE TITLE
LFS quota issue

### ISSUE THREAD

**Issue by ocanam** [issus/altium-library#4]
Hello,

I tried to clone the repo, but unfortunately it failed during the "lfs fetch".
The github server answer with
> batch response: http: This repository is over its data quota. Purchase more data packs to restore access.
> Docs: https://help.github.com/articles/purchasing-additional-storage-and-bandwidth-for-a-personal-account/
> Warning: errors occurred

I plan to setup an altium database so I am interested to see how it looks in the details.
Maybe it is possible for you to share a working version of this repo in an archive via wetransfer or something like that?

Regards

**Comment by issus** [comment]
See readme. I do not have another way to transfer files.
