### ISSUE TITLE
Access from China

### ISSUE THREAD

**Issue by menesesleonardo** [issus/altium-library#44]
Hi, I found that the access to the database from China is not possible. When opening the file Altium hangs for a long time to the point it stops working. If the db is installed as a library, when placing a component hangs for long time and then the lists are empty. Some days ago I went to Macau and everything loaded perfectly, but when I came back to mainland it immediately stopped working.

Windows 10 x64
Altium 20.0.11

**Comment by issus** [comment]
Sounds like something is blocking access to the mssql port, it could be
your isp, or your government. I can only suggest you try a vpn service, as
the issue is not from our end.
