### ISSUE TITLE
Mouser Supplier Link

### ISSUE THREAD

**Issue by mumairanwar92** [issus/altium-library#46]
Hi, I couldn't find the supplier information except for digikey. Is there any help you guys can provide so I can add mouser entries in the database for the components I'm using?

**Comment by issus** [comment]
We're still working on the functionality for additional suppliers, and hope to have that implemented by the end of the month

**Comment by mumairanwar92** [comment]
> We're still working on the functionality for additional suppliers, and hope to have that implemented by the end of the month

Hi, sorry for bothering again. Is there any update for the mouser supplier links ?

**Comment by issus** [comment]
Hi, sorry for the late reply, i've been moving house.

We're currently just starting beta testing of mouser data collection. It's going to be a few more weeks of work.

**Comment by aXe-88** [comment]
Hi, so how do other supplier links work?
