### ISSUE TITLE
A problem with the database

### ISSUE THREAD

**Issue by Pokry** [issus/altium-library#5]
Hello ! ;)
I downloaded "altium-library" repository on disk. I would like to open the file "Celestial Library Database. DbLib", however, is not possible. 

At the beginning i open Celestial Library Database in Altium, the next step
I removed from file mssql sample conn.udl**.txt** to -> mssql sample conn.udl 
and  i choose then I chose the mssql sample conn.udl

![bez tytulu](https://cloud.githubusercontent.com/assets/11419722/21639056/6ba6b834-d26e-11e6-854a-2e0a6d452a64.png)

Can you explain how to access the database? 

Studying at the Wroclaw University of Science and Technology and I have access to Microsoft Azure from Microsoft MSDN.

Thank you so much for all the help :).

**Comment by issus** [comment]
You need to setup a database to connect to. The mssql sample conn.udl is exactly that.. just a sample UDL file with no real connection string. As it says... check your connection settings :)

Please see the top of the readme:
https://github.com/issus/altium-library#need-access-to-azuredont-want-to-setup-your-own-local-mssql-database
