### ISSUE TITLE
Since I pulled the latest update, it took a long time to open Altium. 

### ISSUE THREAD

**Issue by feijie825** [issus/altium-library#56]
Since I pulled the latest update, it took a long time to open Altium. And Altium always loses response. Has anyone else encountered this problem?

**Comment by emileakbarzadeh** [comment]
I am encountering the same issue, where after installing and using components from the library, altium has become extremely laggy. My internet may also be to blame here, since it is extremely slow, however even placing wires in schematic editor has slowed down heavily.

**Comment by XiaoSenLuo** [comment]
so do I, I have removed this library from altium designer, because when I install this library, the X2.exe is not response when startup it.

**Comment by stawiski** [comment]
Same here! It takes long to open but eventually opens for me. Uninstalling the library speeds things up instantly.

**Comment by issus** [comment]
I strong suggest everyone to contact Altium support or post into Altium's BugCrunch. Looking through usage stats and server performance, it's not on my end, this is just Altium.

We're working on an altium extension to replace the components panel, which should help with issues like this and other Altium performance issues.
