### ISSUE TITLE
Is there an automated way of generating the symbol/footprint images?

### ISSUE THREAD

**Issue by sargsyanga** [issus/altium-library#58]
Hi,

I am new to this library and still exploring the capabilities, however I intend keeping the symbol/footprint library in sync with the images in PNG format.

Is there an easy/automated way for generating the image of the symbols/footprints after they are added to the library?

I typical scenario would be adding bunch of new components to the library and running a script/tool to generate the images for the new components in "images" folder.

Thank you in advance

**Comment by currentleak** [comment]
in Altium, with library opened... select Report-Librairy Report

**Comment by issus** [comment]
See my AltiumSharp project, this is what I use to generate the images in the library automatically.

https://github.com/issus/AltiumSharp
