### ISSUE TITLE
Wrong parameters in inductor library

### ISSUE THREAD

**Issue by XaviOndono** [issus/altium-library#64]
There's a lot of components on the inductors - RF table which have the "Package / case" set to
`0402 (1006 Metric)`
This is probably a typo and should read:
`0402 (1005 Metric)`

**Comment by issus** [comment]
There are many cases where an imperial size just gets rounded (40 thou by 20 thou inches) but the metric size is able to be more precise, so the sizes look like they could be a mistake, but if you check the datasheet the metric size is actually correct.

In this case, 0.5mm is 0.01968in, and 0.6mm is 0.02362in, so both get rounded to "02" for the imperial component size.
