### ISSUE TITLE
BM04B-SRSS-TB(LF)(SN) has wrong footprint.

### ISSUE THREAD

**Issue by langetacuna** [issus/altium-library#65]
![cap](https://user-images.githubusercontent.com/3507067/87746575-2b205e80-c7ae-11ea-9464-09d090f4fe97.PNG)

It should look like this:

![rig](https://user-images.githubusercontent.com/3507067/87746682-69b61900-c7ae-11ea-9038-d5d3e43cb207.PNG)

**Comment by issus** [comment]
Fixed, thanks for letting me know!
