### ISSUE TITLE
Resetting the dblib file causes ODBC error

### ISSUE THREAD

**Issue by kyuhyong** [issus/altium-library#70]
I am using altium 17 and was able to add the library successfully and no problem so far. 
However my disk is getting full and wanted to change the library folder so I removed the dblib file in the "Available Libraries" menu as below
![image](https://user-images.githubusercontent.com/22294429/91371798-fdb6de00-e84c-11ea-83ce-31400594bf35.png)
And then copy everything in the altium-library folder into different location and install the dblib file again.
But after that, I am only getting these message saying 
"EOleException error executing:
Select * From [Whatever parts]
Cannot find supplier. May not installed properly"
as below
![image](https://user-images.githubusercontent.com/22294429/91371714-b7fa1580-e84c-11ea-9940-2e9e55e4a261.png)

It seems like Altium is still trying to find the old DB instead of new one. How can I solve this issue?
Thanks,

**Comment by issus** [comment]
Have you tried restarting Altium?

**Comment by kyuhyong** [comment]
> Have you tried restarting Altium?

Yes I did but no difference.

**Comment by issus** [comment]
Altium issues like this should be reported to Altium, use Bug Crunch (https://bugcrunch.live.altium.com/) or contact support - unfortunately there's nothing we can do as it was working previously... so I don't have any suggestions.
