### ISSUE TITLE
Wrong value in two Ceramic Caps

### ISSUE THREAD

**Issue by ing-kuczmik** [issus/altium-library#71]
CAP CER 1UF 35V X5R 0402
C1005X5R1V105K050BC

and

CAP CER 1UF 35V X5R 0402
C1005X5R1V105M050BC

Has some mm as value in the Parameters.

![image](https://user-images.githubusercontent.com/1220909/91560923-f3730d80-e93a-11ea-9cf5-df6db4da7557.png)

**Comment by issus** [comment]
This was reported on discord after the new version of the crawler was run.
We believe we have found the issue and are going to we if we can get it
fixed today!

**Comment by issus** [comment]
The height/thickness issue has been resolved, but it looks as though most caps which were erroneous now do not have a capacitance value... so we're still looking into it.

**Comment by issus** [comment]
Capacitance and Voltage values back to what they should be!
