### ISSUE TITLE
Execution error

### ISSUE THREAD

**Issue by davood-dorostkar** [issus/altium-library#73]
I use Altium 14, and Imported the library. unfortunately, nothing can be loaded and this execution error comes up:

![Capture](https://user-images.githubusercontent.com/44213441/92301264-6aca2200-ef77-11ea-8be9-04c6e5295fc0.JPG)

the same error for all components. 
is it related to the Altium version or something?

**Comment by issus** [comment]
You need to use the DbLib downloaded from the portal, not the one in the repo.
