### ISSUE TITLE
Finding Parts in Altium

### ISSUE THREAD

**Issue by GentleRV** [issus/altium-library#79]
I see parts from the celestrial databse in Altium, but not all parts
Like a IC with partnumber ISO5852SDWR which is a gated driver from TI can be found under the TI manufacturers in the online database but not as part under gatedrivers or in any other libraries
So are many more parts who are in the online database to find but not in Altium.

Is this a error or you are still busy to add those parts to the database?

**Comment by issus** [comment]
As the page you are finding those components on states - that is just the manufacturer data we have, it is not a list of components in the library itself. There's about 5 million components listed on those pages - as an open source library with no income or funding we really can't hope to have full coverage of every component on the market (as much as we'd love to) - I just don't have the resources to do that.
