### ISSUE TITLE
Which database file to use?

### ISSUE THREAD

**Issue by jpelletier** [issus/altium-library#84]
The one here:
https://github.com/issus/altium-library/blob/master/Altium%20Database%20Library%20V2.DbLib

or the one here:
https://portal.altiumlibrary.com/Database/Login ?

The portal one works, but the github doesn't. Do I need a local SQL server?

**Comment by issus** [comment]
The one on github is a template. The one from the portal is the only one with credentials to access the database, it's generated specifically for you.
