### ISSUE TITLE
Converted .IntLib version for CircuitStudio

### ISSUE THREAD

**Issue by fxtentacle** [issus/altium-library#88]
The current .DbLib is not working with CircuitStudio. 

According to
https://www.element14.com/community/docs/DOC-83260/l/altium-circuitstudio-faqs
the current .DbLib could be converted into an .IntLib file, which would then work.

But doing so requires someone with access to "Altium NEXUS". Would anyone be willing to convert the library and add the resulting file as a GitHub release?

**Comment by issus** [comment]
Unfortunately as soon as anything changes in the database, the IntLib would be out of date. Without a way to auto-generate an IntLib we can't add this functionality, as the intlib coudl be going out of sync with the dblib multiple times a day.
