### ISSUE TITLE
BEC or ESC for servo motor

### ISSUE THREAD

**Issue by s-amal** [issus/altium-library#89]
Hi everyone, I'm new to altium, and ive been looking for the components BEC or ESC to use between battery and and servo motor, and i cant seem to find any things like that.
Anyone how has an idea if i have to make them myself or is there a module pre made, im still learning ..?

**Comment by Yarenborta** [comment]
Can you share with me what you learned if you find something about altium
library ?

4 Haz 2021 Cum 16:15 tarihinde s-amal ***@***.***> şunu yazdı:

**Comment by issus** [comment]
Not an issue with this project. Please see discord for help with your designs.
