### ISSUE TITLE
Connect to Azure failed

### ISSUE THREAD

**Issue by zsserg** [issus/altium-library#9]
Hi!
I've done all the setup through desktop tool as described [here](https://github.com/issus/CelestialADB-Desktop), cloned the repo, but Altium still wouldn't connect to the database (see screenshot attached).
![default](https://cloud.githubusercontent.com/assets/16120171/26686340/8970a75e-46e4-11e7-9d13-19488f512393.PNG)
 Can this be a server-side problem?

**Comment by issus** [comment]
Did you just create an account? I had an exception about 50 minutes before your issue was created:

```
New exception at setting database roles on Thursday, June 1, 2017 2:16:08 PM (note: no idea what timezone this is!)

Message: An error was reported while committing a database transaction but it could not be determined whether the transaction succeeded or failed on the database server. See the inner exception and http://go.microsoft.com/fwlink/?LinkId=313468 for more information.


---- INNER EXCEPTION ----

Message: Execution Timeout Expired. The timeout period elapsed prior to completion of the operation or the server is not responding.
```

If that's the case, you dont have a database role, and i'll have to create it manually for you

**Comment by zsserg** [comment]
Yes, it was about an hour ago. The connection test tool fails with timeout error:
![default](https://cloud.githubusercontent.com/assets/16120171/26687322/57b772bc-46e7-11e7-931c-230f005bc6d8.PNG)
I do see connection attempt, but Azure server does not seem to respond:
![aq](https://cloud.githubusercontent.com/assets/16120171/26687350/6529ca58-46e7-11e7-846b-f0072494478b.PNG)

**Comment by zsserg** [comment]
OK, I seem to partially find the reason - blocked outgoing TCP/1433. If I forward it through remote ssh server (local 1433 -> ssh tunnel -> Azure 1433) I am getting other error message - this time Azure firewall is obviously blocking unknown IP. Wrote to uni it-support to see if it would be possible to unblock outgoing TCP.

**Comment by issus** [comment]
Ah yes, Universities love to block outbound SQL connections. Your IT department should be able to help you out.

**Comment by zsserg** [comment]
Just to confirm - indeed it was uni firewall blocking outgoing TCP/1433. Sorry for bothering. ;)
